modLoader="javafml"
loaderVersion="[43,)"
license="GPL3.0"

[[mods]]
modId="techniq"
version="${file.jarVersion}"
displayName="Techniq"
logoFile="logo.png"
authors="neariyeveryone, kimunachan"
description='''
'''